# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftWeather' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking'
  # Pods for SwiftWeather

  target 'SwiftWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftWeatherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
